name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate
      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Terraform Security Scan
        run: |
            checkov -d . --framework terraform
      # ==================================================
      # 7. Gitleaks - Secret Detection
      # ==================================================

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
      - name: Gitleaks Scan start
        run: |
          gitleaks git --verbose

      # ==================================================
      # 8. TFLint - Terraform Linting
      # ==================================================

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint Init
        run: tflint --init

      - name: TFLint Scan
        run: tflint --recursive
      # ==================================================
      # 9. tfsec - Terraform Security
      # ==================================================

      - name: tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: false
        # ==================================================
      # 10. Trivy - Infrastructure Security Scan
      # ==================================================

      - name: Trivy Terraform Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1


      - name: Terraform Plan
        run: terraform plan